spring:
  application:
   name: crebit-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: abhi
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or create, create-drop, validate based on your needs
      dialect: org.hibernate.dialect.PostgreSQLDialect  # Add this line
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user
      password: password
